### ISSUE TITLE
建議增加各種 example

### ISSUE THREAD

**Issue by shihyuho** [Chris-Tsai/zipcode-tw-react#4]
例如 [iris](https://github.com/kataras/iris/) 是一個 golan 的 web framework, 但在他根目錄下有一個 [_example](https://github.com/kataras/iris/tree/master/_examples) 目錄, 裡面直接放了各種範例程式碼, 對於一個框架 or 元件來說, 會讓人更容易更快速的理解, 提供範例程式碼也會更容易的推廣出去

**Comment by Chris-Tsai** [comment]
我會盡快補上，感謝
